const fs = require('fs');
const file = 'd:/ĐỒ ÁN/Green Trip/src/pages/LandingPage.tsx';
let content = fs.readFileSync(file, 'utf8');

const oldHue = /<div className="w-\\[90%\\] bg-white rounded-3xl shadow-xl border border-gray-100 p-4 relative">\\s*<div className="flex justify-between items-center mb-4">\\s*<div className="text-xs font-bold text-black">Lịch trình Huế 3 ngày<\/div>\\s*<div className="w-6 h-6 rounded-full bg-blue-100 text-\\[10px\\] flex items-center justify-center font-bold">\+<\/div>\\s*<\/div>\\s*<div className="space-y-3">\\s*<div className="flex gap-3 items-center">\\s*<div className="w-2\\.5 h-2\\.5 rounded-full bg-blue-500"><\/div>\\s*<div className="flex-1 space-y-1\\.5"><div className="h-2 w-\\[70%\\] bg-gray-200 rounded-full"><\/div><div className="h-1\\.5 w-\\[40%\\] bg-gray-100 rounded-full"><\/div><\/div>\\s*<\/div>\\s*<div className="flex gap-3 items-center">\\s*<div className="w-2\\.5 h-2\\.5 rounded-full bg-gray-300"><\/div>\\s*<div className="flex-1 space-y-1\\.5"><div className="h-2 w-\\[50%\\] bg-gray-200 rounded-full"><\/div><div className="h-1\\.5 w-\\[80%\\] bg-gray-100 rounded-full"><\/div><\/div>\\s*<\/div>\\s*<div className="flex gap-3 items-center">\\s*<div className="w-2\\.5 h-2\\.5 rounded-full bg-gray-300"><\/div>\\s*<div className="flex-1 space-y-1\\.5"><div className="h-2 w-\\[90%\\] bg-gray-200 rounded-full"><\/div><div className="h-1\\.5 w-\\[30%\\] bg-gray-100 rounded-full"><\/div><\/div>\\s*<\/div>\\s*<\/div>\\s*<\/div>/;

const newHue = '<div className="w-[80%] bg-white rounded-3xl shadow-2xl border border-gray-100 p-3 relative translate-y-2"><div className="flex justify-between items-center mb-3"><div className="text-[11px] font-bold text-black">Lịch trình Huế 3 ngày</div><div className="w-5 h-5 rounded-full bg-blue-100 text-[9px] flex items-center justify-center font-bold">+</div></div><div className="space-y-2.5"><div className="flex gap-2 items-center"><div className="w-2 h-2 rounded-full bg-blue-500"></div><div className="flex-1 space-y-1"><div className="h-1.5 w-[70%] bg-gray-200 rounded-full"></div><div className="h-1 w-[40%] bg-gray-100 rounded-full"></div></div></div><div className="flex gap-2 items-center"><div className="w-2 h-2 rounded-full bg-gray-300"></div><div className="flex-1 space-y-1"><div className="h-1.5 w-[50%] bg-gray-200 rounded-full"></div><div className="h-1 w-[80%] bg-gray-100 rounded-full"></div></div></div><div className="flex gap-2 items-center"><div className="w-2 h-2 rounded-full bg-gray-300"></div><div className="flex-1 space-y-1"><div className="h-1.5 w-[90%] bg-gray-200 rounded-full"></div><div className="h-1 w-[30%] bg-gray-100 rounded-full"></div></div></div></div></div>';

content = content.replace(oldHue, newHue);

const oldMap = /<div className="absolute -bottom-8 left-0 right-0 flex justify-center pointer-events-none">\\s*<div className="relative w-\\[90%\\] rotate-\\[2deg\\]">\\s*<img src="https:\/\/images\\.unsplash\\.com\/photo-1559592413-7cecaedfb3ff\\?auto=format&fit=crop&q=80" className="w-full h-36 object-cover rounded-3xl shadow-xl" \/>\\s*<div className="absolute bottom-3 left-3 bg-white\/95 backdrop-blur-sm px-3 py-1\\.5 rounded-xl shadow-sm">\\s*<div className="text-\\[11px\\] font-bold text-black">Cầu Rồng<\/div>\\s*<div className="text-\\[9px\\] text-gray-500 font-medium">Đà Nẵng<\/div>\\s*<\/div>\\s*<div className="absolute -top-4 -right-2 w-12 h-12 bg-black rounded-full shadow-2xl flex items-center justify-center border-4 border-white">\\s*<MapPin size=\\{18\\} className="text-white" \/>\\s*<\/div>\\s*<\/div>\\s*<\/div>/;

const newMap = '<div className="absolute -bottom-10 left-0 right-0 flex justify-center items-center pointer-events-none"><div className="absolute w-[75%] rotate-[-6deg] translate-x-[-15px] translate-y-[0px] z-0"><img src="https://images.unsplash.com/photo-1580837119756-563d608ca11a?auto=format&fit=crop&q=80" className="w-full h-28 object-cover rounded-[24px] shadow-lg border-[3px] border-white" /><div className="absolute bottom-2 left-2 bg-white/95 backdrop-blur-sm px-2 py-1 rounded-lg shadow-sm"><div className="text-[9px] font-bold text-black">Đại Nội</div><div className="text-[7px] text-gray-500 font-medium">Huế</div></div></div><div className="relative w-[80%] rotate-[4deg] translate-x-[15px] z-10 translate-y-[-10px]"><img src="https://images.unsplash.com/photo-1555921015-c262060f64be?auto=format&fit=crop&q=80" className="w-full h-32 object-cover rounded-[24px] shadow-2xl border-[3px] border-white" /><div className="absolute bottom-3 left-3 bg-white/95 backdrop-blur-sm px-3 py-1.5 rounded-xl shadow-sm"><div className="text-[11px] font-bold text-black">Phố Cổ</div><div className="text-[9px] text-gray-500 font-medium">Hội An</div></div><div className="absolute -top-3 -right-3 w-10 h-10 bg-black rounded-full shadow-xl flex items-center justify-center border-[3px] border-white"><MapPin size={16} className="text-white" /></div></div></div>';

content = content.replace(oldMap, newMap);

fs.writeFileSync(file, content);
console.log('Fixed cards completely');
